name: math
on: push

jobs: 
  m_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Get python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: install lib
        run: pip install numpy
      - name: run code
        run: python mt.py

  m1_test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4
      - name: Get python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install lib
        run: pip install numpy
      - name: run code
        run: python mt.py
        

